### ISSUE TITLE
Como cria o pagamento por cartão de crédito ou por pix?

### ISSUE THREAD

**Issue by vinifr** [eduardo-mior/mercadopago-sdk-go#1]
Em CreatePayment não se especifica o método de pagamento?

**Comment by eduardo-mior** [comment]
@vinifr mais ou menos...

CreatePayment serve basicamente pra criar um Link de Pagamento, e quando o usuário acessar esse seu Link de Pagamento ele vai poder escolher como ele quer pagar, por Pix ou por Cartão ou por Boleto etc...

Oque você pode fazer se eu não me engano, é usar o atributo "PaymentMethods" e configurar os métodos de pagamentos que você quer excluir, ou seja, que você não quer deixar habilitado.

Então se você só quiser deixar habilitado para que o usuário pague somente com boleto, então você tem que ir no PaymentMethods e configurar que você quer "excluir" os outros meios de pagamento (cartão, pix etc..)

**Comment by vinifr** [comment]
Ok. Obrigado.
