### ISSUE TITLE
Não consigo pagar com o link gerado 

### ISSUE THREAD

**Issue by vinifr** [eduardo-mior/mercadopago-sdk-go#2]
Olá, estou gerando o link e quando tento pagar por Pix, dá chave inexistente e quando tento por cartão, o cartão recusa. Mas está mostrando as informações de compra corretas.

Qual poderia ser o problema? Testei com a chave de teste e também com a chave real.

**Comment by vinifr** [comment]
func createPayLink(price float64, title string, CPF string) string {

    response, mercadopagoErr, err := mercadopago.CreatePayment(mercadopago.PaymentRequest{
        ExternalReference: "4833556173215xxx",
        Items: []mercadopago.Item{
            {
                Title:     title,
                Quantity:  1,
                UnitPrice: price,
            },
        },
        Payer: mercadopago.Payer{
            Identification: mercadopago.PayerIdentification{
                Type:   "CPF",
                Number: CPF,
            },
            //Email:   email,
        },
        NotificationURL:   "https://api.bot.com.br/api/payment",
    }, "APP_USR-483355617321yyy-060405-d27c81d3ec41dbde12c07ec2282c78f2-xx")

    //fmt.Println("response = ", response)
    if err != nil {
        // Erro inesperado
        log.Fatal(err)
        return ""
    } else if mercadopagoErr != nil {
        // Erro retornado do MercadoPago
        log.Fatal(mercadopagoErr)
        return ""
    } else {
        //log.Println(response.InitPoint) // Sucesso!
    }
    return response.InitPoint;
}

**Comment by eduardo-mior** [comment]
@vinifr não sei se você esta testando em Homologação (staging) ou em Produção, se não me engano em Homologação só da pra pagar com os cartões de crédito de testes do mercado pago mesmo, na documentação deles tem um lugar onde eles tem varios números de cartão de crédito de testes.

Em produção é pra funcionar tudo normal.

**Comment by vinifr** [comment]
Testei com o token de teste e o token de produção, nenhuma funcionou. Aliás, onde coloca a Public Key? Será que não faltou isso?

**Comment by eduardo-mior** [comment]
@vinifr a unica coisa que precisa pra funcionar é o AccessToken, a PublicKey é para caso você queira fazer o seu próprio Checkout criando seu próprio FrontEnd até onde eu sei

**Comment by vinifr** [comment]
Blz, está funcionando. O erro é quando coloca um  CPF que não tem conta no mercado pago.

Vlw.
