### ISSUE TITLE
Json da Consulta de pagamento mudou

### ISSUE THREAD

**Issue by vinifr** [eduardo-mior/mercadopago-sdk-go#3]
Olá. A resposta de API do mercado pago pra consulta de pagamento mudou mas seu modelo deve estar usando o antigo, na parte de Payer. Está assim agora:

"payer": {
    "id": 123,
    "email": "afriend@gmail.com",
    "identification": {
      "type": "DNI",
      "number": 12345678
    },
    "type": "customer"
  },

O identification/number é tipo int mas no seu modelo está string:

type PayerIdentification struct {
	Type   string `json:"type"`   // Tipo do documento de identificação (use CPF ou CNPJ)
	Number string `json:"number"` // Número do documentação de identificação
}

**Comment by vinifr** [comment]
Esquece, o CPF é realmente string, mas não aparece na documentação.

**Comment by eduardo-mior** [comment]
@vinifr a documentação do mercado pago é bem falha mesmo, varios campos estão documentados como Int mas na pratica são como String, ou em alguns caso, no POST vc manda uma Int e no GET retorna como String oque não faz o menor sentido.

Varios campos também nem estão documentados... é triste kkkk
